CREATE TABLE `sure_trade_db`.`Currencies` (
                                              `id` int NOT NULL AUTO_INCREMENT,
                                              `name` varchar(255) NOT NULL,
                                              `symbol` varchar(255) DEFAULT NULL,
                                              `currencyType` varchar(255) NOT NULL,
                                              `createdAt` datetime NOT NULL,
                                              `updatedAt` datetime DEFAULT NULL,
                                              PRIMARY KEY (`id`),
                                              UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

create table if not exists `Adverts` (
                           `id` bigint NOT NULL AUTO_INCREMENT,
                           `title` varchar(255) NOT NULL,
                           `description` varchar(255) NOT NULL,
                           `imageUrls` varchar(255) DEFAULT NULL,
                           `url` varchar(255) DEFAULT NULL,
                           `status` varchar(255) DEFAULT NULL,
                           `createdAt` datetime NOT NULL,
                           `updatedAt` datetime NOT NULL,
                           primary key (`id`),
                           unique key `id` (`id`)
);

CREATE TABLE `sure_trade_db`.`GiftCardRates` (
                                                 `id` bigint NOT NULL AUTO_INCREMENT,
                                                 `cardName` varchar(255) DEFAULT NULL,
                                                 `merchantId` bigint NOT NULL,
                                                 `currency` varchar(255) NOT NULL,
                                                 `giftCardCurrency` varchar(255) DEFAULT NULL,
                                                 `giftCardType` varchar(255) DEFAULT NULL,
                                                 `transactionType` varchar(255) DEFAULT NULL,
                                                 `paymentMethod` varchar(255) DEFAULT NULL,
                                                 `bankDetailsId` bigint DEFAULT NULL,
                                                 `walletAddressId` bigint DEFAULT NULL,
                                                 `maxLimit` decimal(10,2) DEFAULT NULL,
                                                 `minLimit` decimal(10,2) DEFAULT NULL,
                                                 `rate` decimal(10,2) NOT NULL,
                                                 `status` varchar(255) NOT NULL,
                                                 `screenshots` json DEFAULT NULL,
                                                 `createdAt` datetime NOT NULL DEFAULT '2023-09-23 15:02:16',
                                                 `updatedAt` datetime DEFAULT NULL,
                                                 PRIMARY KEY (`id`),
                                                 UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`News` (
                                        `id` bigint NOT NULL AUTO_INCREMENT,
                                        `title` varchar(255) DEFAULT NULL,
                                        `subTitle` text,
                                        `content` longtext,
                                        `subContent` longtext,
                                        `images` json DEFAULT NULL,
                                        `video` json DEFAULT NULL,
                                        `userId` bigint DEFAULT NULL,
                                        `isRead` tinyint(1) DEFAULT NULL,
                                        `createdAt` datetime NOT NULL,
                                        `updatedAt` datetime NOT NULL,
                                        PRIMARY KEY (`id`),
                                        UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Payments` (
                                            `id` bigint NOT NULL AUTO_INCREMENT,
                                            `userId` bigint DEFAULT NULL,
                                            `merchantId` bigint DEFAULT NULL,
                                            `transactionId` bigint NOT NULL,
                                            `amount` decimal(10,2) NOT NULL,
                                            `screenshots` varchar(255) DEFAULT NULL,
                                            `currency` varchar(255) NOT NULL,
                                            `paymentMethod` varchar(255) DEFAULT NULL,
                                            `paymentStatus` varchar(255) NOT NULL,
                                            `paymentDate` date NOT NULL,
                                            `paymentReference` varchar(255) DEFAULT NULL,
                                            `paymentDescription` varchar(255) DEFAULT NULL,
                                            `paymentType` varchar(255) DEFAULT NULL,
                                            `productType` varchar(255) DEFAULT NULL,
                                            `bankDetailsId` bigint DEFAULT NULL,
                                            `walletAddressId` bigint DEFAULT NULL,
                                            `giftCardId` bigint DEFAULT NULL,
                                            `paidFor` varchar(255) DEFAULT NULL,
                                            `paidTo` json DEFAULT NULL,
                                            `createdAt` datetime NOT NULL,
                                            `updatedAt` datetime DEFAULT NULL,
                                            `transactionHashId` varchar(255) DEFAULT NULL,
                                            `userTransactionHash` varchar(255) DEFAULT NULL,
                                            `merchantTransactionHash` varchar(255) DEFAULT NULL,
                                            PRIMARY KEY (`id`),
                                            UNIQUE KEY `id` (`id`),
                                            KEY `transactionId` (`transactionId`),
                                            KEY `userId` (`userId`),
                                            KEY `merchantId` (`merchantId`),
                                            KEY `bankDetailsId` (`bankDetailsId`),
                                            KEY `walletAddressId` (`walletAddressId`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Referrals` (
                                             `id` bigint NOT NULL AUTO_INCREMENT,
                                             `referrer` bigint NOT NULL,
                                             `referee` bigint NOT NULL,
                                             `referralCode` varchar(100) DEFAULT NULL,
                                             `referralLink` varchar(250) DEFAULT NULL,
                                             `referralType` varchar(100) DEFAULT NULL,
                                             `referralValue` decimal(16,3) DEFAULT NULL,
                                             `expiryDate` date DEFAULT NULL,
                                             `status` varchar(20) DEFAULT NULL,
                                             `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             `updatedAt` datetime DEFAULT NULL,
                                             PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `sure_trade_db`.`SupportedGiftCards` (
                                                      `id` varchar(50) NOT NULL,
                                                      `name` varchar(255) NOT NULL,
                                                      `image` varchar(255) NOT NULL,
                                                      `currency` json NOT NULL,
                                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Tiers` (
                                         `id` bigint NOT NULL AUTO_INCREMENT,
                                         `tierName` varchar(255) NOT NULL,
                                         `tierDescription` varchar(255) DEFAULT NULL,
                                         `stakedAmountRange` varchar(255) DEFAULT NULL,
                                         `noOfTransactions` json DEFAULT NULL,
                                         `noOfReferrals` int DEFAULT NULL,
                                         `referralBonus` float DEFAULT NULL,
                                         `referralBonusType` varchar(255) DEFAULT NULL,
                                         `referralBonusAmount` float DEFAULT NULL,
                                         `referralBonusPercentage` float DEFAULT NULL,
                                         `createdAt` datetime NOT NULL,
                                         `updatedAt` datetime NOT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`TransactionProfiles` (
                                                       `id` bigint NOT NULL AUTO_INCREMENT,
                                                       `userId` bigint DEFAULT NULL,
                                                       `transactionLimit` float DEFAULT NULL,
                                                       `range` varchar(255) DEFAULT NULL,
                                                       `noOfStakings` json DEFAULT NULL,
                                                       `totalNoOfStakings` int DEFAULT NULL,
                                                       `noOfTransactions` json DEFAULT NULL,
                                                       `totalTransactions` int DEFAULT NULL,
                                                       `noOfCompletedTransactions` json DEFAULT NULL,
                                                       `totalNoOfCompletedTransactions` int DEFAULT NULL,
                                                       `noOfCancelledTransactions` json DEFAULT NULL,
                                                       `totalNoOfCancelledTransactions` int DEFAULT NULL,
                                                       `noOfFailedTransactions` json DEFAULT NULL,
                                                       `totalNoOfFailedTransactions` int DEFAULT NULL,
                                                       `noOfPendingTransactions` json DEFAULT NULL,
                                                       `totalNoOfPendingTransactions` int DEFAULT NULL,
                                                       `createdAt` datetime NOT NULL,
                                                       `updatedAt` datetime NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Users` (
                                         `id` bigint NOT NULL AUTO_INCREMENT,
                                         `firstName` varchar(255) DEFAULT NULL,
                                         `lastName` varchar(255) DEFAULT NULL,
                                         `middleName` varchar(255) DEFAULT NULL,
                                         `username` varchar(255) DEFAULT NULL,
                                         `token` text,
                                         `otp` varchar(255) DEFAULT NULL,
                                         `transactionPin` varchar(255) DEFAULT NULL,
                                         `role` varchar(255) NOT NULL,
                                         `walletAddress` varchar(255) DEFAULT NULL,
                                         `nonce` varchar(255) DEFAULT NULL,
                                         `phoneNumber` varchar(255) DEFAULT NULL,
                                         `telegram` varchar(255) DEFAULT NULL,
                                         `profilePicture` varchar(255) DEFAULT NULL,
                                         `address` text,
                                         `city` varchar(255) DEFAULT NULL,
                                         `state` varchar(255) DEFAULT NULL,
                                         `country` varchar(255) DEFAULT NULL,
                                         `gender` varchar(255) DEFAULT NULL,
                                         `email` varchar(255) NOT NULL,
                                         `password` varchar(255) NOT NULL,
                                         `tierId` bigint DEFAULT NULL,
                                         `transactionProfileId` bigint DEFAULT NULL,
                                         `isActive` tinyint(1) NOT NULL,
                                         `isSuspended` tinyint(1) NOT NULL,
                                         `isVerified` tinyint(1) NOT NULL,
                                         `createdAt` datetime NOT NULL,
                                         `updatedAt` datetime DEFAULT NULL,
                                         `referralCodes` json DEFAULT NULL,
                                         `lastSeen` datetime DEFAULT NULL,
                                         `telegramChatId` varchar(250) DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `id` (`id`),
                                         UNIQUE KEY `email` (`email`),
                                         KEY `tierId` (`tierId`),
                                         KEY `transactionProfileId` (`transactionProfileId`),
                                         CONSTRAINT `Users_ibfk_55` FOREIGN KEY (`tierId`) REFERENCES `Tiers` (`id`),
                                         CONSTRAINT `Users_ibfk_56` FOREIGN KEY (`transactionProfileId`) REFERENCES `TransactionProfiles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Wallets` (
                                           `id` bigint NOT NULL AUTO_INCREMENT,
                                           `userId` bigint DEFAULT NULL,
                                           `address` varchar(255) DEFAULT NULL,
                                           `balance` decimal(10,2) NOT NULL,
                                           `currency` varchar(255) NOT NULL,
                                           `status` varchar(255) NOT NULL DEFAULT 'active',
                                           `createdAt` datetime NOT NULL,
                                           `updatedAt` datetime DEFAULT NULL,
                                           PRIMARY KEY (`id`),
                                           KEY `userId` (`userId`),
                                           CONSTRAINT `Wallets_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `sure_trade_db`.`BankDetails` (
                                               `id` bigint NOT NULL AUTO_INCREMENT,
                                               `bankName` varchar(255) DEFAULT NULL,
                                               `accountName` varchar(255) DEFAULT NULL,
                                               `accountNumber` varchar(255) NOT NULL,
                                               `currency` varchar(255) DEFAULT NULL,
                                               `accountType` varchar(255) DEFAULT NULL,
                                               `bankCode` varchar(255) DEFAULT NULL,
                                               `bankCountry` varchar(255) DEFAULT NULL,
                                               `userId` bigint NOT NULL,
                                               `createdAt` datetime NOT NULL,
                                               `updatedAt` datetime DEFAULT NULL,
                                               PRIMARY KEY (`id`),
                                               UNIQUE KEY `id` (`id`),
                                               UNIQUE KEY `accountNumber` (`accountNumber`),
                                               KEY `userId` (`userId`),
                                               CONSTRAINT `BankDetails_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`BecomeMerchantRequests` (
                                                          `id` bigint NOT NULL AUTO_INCREMENT,
                                                          `userId` bigint DEFAULT NULL,
                                                          `userWalletAddress` longtext,
                                                          `transactionHashId` longtext,
                                                          `amount` double DEFAULT NULL,
                                                          `currency` varchar(255) DEFAULT NULL,
                                                          `firstName` varchar(255) DEFAULT NULL,
                                                          `lastName` varchar(255) DEFAULT NULL,
                                                          `email` varchar(255) DEFAULT NULL,
                                                          `phoneNumber` varchar(255) DEFAULT NULL,
                                                          `username` varchar(255) DEFAULT NULL,
                                                          `country` varchar(255) DEFAULT NULL,
                                                          `status` varchar(255) DEFAULT NULL,
                                                          `createdAt` datetime DEFAULT NULL,
                                                          `updatedAt` datetime DEFAULT NULL,
                                                          PRIMARY KEY (`id`),
                                                          UNIQUE KEY `id` (`id`),
                                                          KEY `userId` (`userId`),
                                                          CONSTRAINT `BecomeMerchantRequests_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Chats` (
                                         `id` bigint NOT NULL AUTO_INCREMENT,
                                         `senderId` bigint NOT NULL,
                                         `receiverId` bigint NOT NULL,
                                         `transactionId` bigint DEFAULT NULL,
                                         `giftCardId` bigint DEFAULT NULL,
                                         `cryptoCoinId` bigint DEFAULT NULL,
                                         `assetName` varchar(255) DEFAULT NULL,
                                         `message` varchar(255) DEFAULT NULL,
                                         `screenshots` json DEFAULT NULL,
                                         `isRead` tinyint(1) DEFAULT '0',
                                         `createdAt` datetime NOT NULL,
                                         `updatedAt` datetime DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `sure_trade_db`.`GiftCards` (
                                             `id` bigint NOT NULL AUTO_INCREMENT,
                                             `userId` bigint NOT NULL,
                                             `cardCode` varchar(255) DEFAULT NULL,
                                             `cardPin` varchar(255) DEFAULT NULL,
                                             `cardType` varchar(255) DEFAULT NULL,
                                             `cardIssuer` varchar(255) DEFAULT NULL,
                                             `currency` varchar(255) NOT NULL,
                                             `amount` decimal(16,3) DEFAULT NULL,
                                             `quantity` int DEFAULT NULL,
                                             `cardValue` decimal(16,3) DEFAULT NULL,
                                             `discount` decimal(10,2) DEFAULT NULL,
                                             `expiryDate` date DEFAULT NULL,
                                             `status` varchar(255) DEFAULT NULL,
                                             `screenshots` json DEFAULT NULL,
                                             `createdAt` datetime NOT NULL,
                                             `updatedAt` datetime DEFAULT NULL,
                                             PRIMARY KEY (`id`),
                                             UNIQUE KEY `id` (`id`),
                                             KEY `userId` (`userId`),
                                             CONSTRAINT `GiftCards_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=86 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`GiftCardTransactions` (
                                                        `id` bigint NOT NULL AUTO_INCREMENT,
                                                        `giftCardId` bigint DEFAULT NULL,
                                                        `giftCardRateId` bigint DEFAULT NULL,
                                                        `userId` bigint DEFAULT NULL,
                                                        `merchantId` bigint NOT NULL,
                                                        `transactionType` varchar(255) NOT NULL,
                                                        `cardType` varchar(255) DEFAULT NULL,
                                                        `cardIssuer` varchar(255) DEFAULT NULL,
                                                        `paymentMethod` varchar(255) DEFAULT NULL,
                                                        `bankDetailsId` bigint DEFAULT NULL,
                                                        `walletAddressId` bigint DEFAULT NULL,
                                                        `amount` decimal(10,2) NOT NULL,
                                                        `quantity` int NOT NULL,
                                                        `fee` decimal(10,2) NOT NULL,
                                                        `currency` varchar(255) NOT NULL,
                                                        `referenceNo` varchar(255) DEFAULT NULL,
                                                        `status` varchar(255) NOT NULL,
                                                        `createdAt` datetime NOT NULL,
                                                        `updatedAt` datetime DEFAULT NULL,
                                                        PRIMARY KEY (`id`),
                                                        UNIQUE KEY `id` (`id`),
                                                        KEY `giftCardId` (`giftCardId`),
                                                        KEY `giftCardRateId` (`giftCardRateId`),
                                                        KEY `userId` (`userId`),
                                                        KEY `merchantId` (`merchantId`),
                                                        KEY `bankDetailsId` (`bankDetailsId`),
                                                        KEY `walletAddressId` (`walletAddressId`),
                                                        CONSTRAINT `GiftCardTransactions_ibfk_151` FOREIGN KEY (`giftCardId`) REFERENCES `GiftCards` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                        CONSTRAINT `GiftCardTransactions_ibfk_152` FOREIGN KEY (`giftCardRateId`) REFERENCES `GiftCardRates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                        CONSTRAINT `GiftCardTransactions_ibfk_153` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                                                        CONSTRAINT `GiftCardTransactions_ibfk_154` FOREIGN KEY (`merchantId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                                                        CONSTRAINT `GiftCardTransactions_ibfk_155` FOREIGN KEY (`bankDetailsId`) REFERENCES `BankDetails` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                        CONSTRAINT `GiftCardTransactions_ibfk_156` FOREIGN KEY (`walletAddressId`) REFERENCES `Wallets` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=141 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Rates` (
                                         `id` bigint NOT NULL AUTO_INCREMENT,
                                         `merchantId` bigint DEFAULT NULL,
                                         `transactionType` varchar(255) DEFAULT NULL,
                                         `maxLimit` decimal(10,2) DEFAULT NULL,
                                         `minLimit` decimal(10,2) DEFAULT NULL,
                                         `currency` varchar(255) DEFAULT NULL,
                                         `assetName` varchar(255) DEFAULT NULL,
                                         `rate` float DEFAULT NULL,
                                         `sellRate` float DEFAULT NULL,
                                         `buyRate` float DEFAULT NULL,
                                         `margin` float DEFAULT NULL,
                                         `standardRate` float DEFAULT NULL,
                                         `productName` varchar(255) DEFAULT NULL,
                                         `discount` float DEFAULT NULL,
                                         `paymentMethod` varchar(255) DEFAULT NULL,
                                         `bankDetailsId` bigint DEFAULT NULL,
                                         `walletAddressId` bigint DEFAULT NULL,
                                         `createdAt` datetime DEFAULT NULL,
                                         `updatedAt` datetime DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `id` (`id`),
                                         KEY `merchantId` (`merchantId`),
                                         KEY `bankDetailsId` (`bankDetailsId`),
                                         KEY `walletAddressId` (`walletAddressId`),
                                         CONSTRAINT `Rates_ibfk_79` FOREIGN KEY (`merchantId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                                         CONSTRAINT `Rates_ibfk_80` FOREIGN KEY (`bankDetailsId`) REFERENCES `BankDetails` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                         CONSTRAINT `Rates_ibfk_81` FOREIGN KEY (`walletAddressId`) REFERENCES `Wallets` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`Rating` (
                                          `id` bigint NOT NULL AUTO_INCREMENT,
                                          `userId` bigint NOT NULL,
                                          `raterId` bigint NOT NULL,
                                          `rating` double NOT NULL,
                                          `comment` varchar(255) DEFAULT NULL,
                                          `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                          `updatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          PRIMARY KEY (`id`),
                                          KEY `userId` (`userId`),
                                          KEY `raterId` (`raterId`),
                                          CONSTRAINT `Rating_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`),
                                          CONSTRAINT `Rating_ibfk_2` FOREIGN KEY (`raterId`) REFERENCES `Users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `sure_trade_db`.`StakedAssets` (
                                                `id` bigint NOT NULL AUTO_INCREMENT,
                                                `userId` bigint DEFAULT NULL,
                                                `tierId` bigint DEFAULT NULL,
                                                `adminId` bigint DEFAULT NULL,
                                                `transactionHashId` longtext,
                                                `userWalletAddress` longtext,
                                                `adminWalletAddress` longtext,
                                                `currency` varchar(255) DEFAULT NULL,
                                                `amount` double NOT NULL,
                                                `balance` double DEFAULT NULL,
                                                `previousBalance` double DEFAULT NULL,
                                                `status` varchar(255) NOT NULL,
                                                `createdAt` datetime NOT NULL,
                                                `updatedAt` datetime DEFAULT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE KEY `id` (`id`),
                                                KEY `userId` (`userId`),
                                                CONSTRAINT `StakedAssets_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`StakeWithdrawalRequests` (
                                                           `id` bigint NOT NULL AUTO_INCREMENT,
                                                           `userId` bigint DEFAULT NULL,
                                                           `paymentMethod` varchar(255) DEFAULT NULL,
                                                           `bankDetailsId` bigint DEFAULT NULL,
                                                           `walletAddressId` bigint DEFAULT NULL,
                                                           `stakedAssetId` bigint DEFAULT NULL,
                                                           `paymentCurrency` varchar(255) DEFAULT NULL,
                                                           `amount` float NOT NULL,
                                                           `reasonForWithdrawal` varchar(255) DEFAULT NULL,
                                                           `withdrawalFee` float DEFAULT NULL,
                                                           `status` varchar(255) NOT NULL,
                                                           `createdAt` datetime NOT NULL,
                                                           `updatedAt` datetime DEFAULT NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE KEY `id` (`id`),
                                                           KEY `userId` (`userId`),
                                                           CONSTRAINT `StakeWithdrawalRequests_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `sure_trade_db`.`Transactions` (
                                                `id` bigint NOT NULL AUTO_INCREMENT,
                                                `userId` bigint DEFAULT NULL,
                                                `merchantId` bigint DEFAULT NULL,
                                                `rateId` bigint DEFAULT NULL,
                                                `assetName` varchar(255) DEFAULT NULL,
                                                `currency` varchar(255) DEFAULT NULL,
                                                `amount` float DEFAULT NULL,
                                                `unitPrice` float DEFAULT NULL,
                                                `quantity` int DEFAULT NULL,
                                                `transactionFee` float DEFAULT NULL,
                                                `transactionType` varchar(255) DEFAULT NULL,
                                                `productName` varchar(255) DEFAULT NULL,
                                                `paymentMethod` varchar(255) DEFAULT NULL,
                                                `bankDetailsId` bigint DEFAULT NULL,
                                                `walletAddressId` bigint DEFAULT NULL,
                                                `userTransactionHash` varchar(255) DEFAULT NULL,
                                                `merchantTransactionHash` varchar(255) DEFAULT NULL,
                                                `discount` float DEFAULT NULL,
                                                `type` varchar(255) DEFAULT NULL,
                                                `status` varchar(255) DEFAULT NULL,
                                                `description` varchar(255) DEFAULT NULL,
                                                `screenshots` json DEFAULT NULL,
                                                `referenceNo` varchar(255) DEFAULT NULL,
                                                `createdAt` datetime NOT NULL,
                                                `updatedAt` datetime DEFAULT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE KEY `id` (`id`),
                                                KEY `userId` (`userId`),
                                                KEY `merchantId` (`merchantId`),
                                                KEY `rateId` (`rateId`),
                                                KEY `bankDetailsId` (`bankDetailsId`),
                                                KEY `walletAddressId` (`walletAddressId`),
                                                CONSTRAINT `Transactions_ibfk_130` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                CONSTRAINT `Transactions_ibfk_131` FOREIGN KEY (`merchantId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                CONSTRAINT `Transactions_ibfk_132` FOREIGN KEY (`rateId`) REFERENCES `Rates` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                CONSTRAINT `Transactions_ibfk_133` FOREIGN KEY (`bankDetailsId`) REFERENCES `BankDetails` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                                CONSTRAINT `Transactions_ibfk_134` FOREIGN KEY (`walletAddressId`) REFERENCES `Wallets` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sure_trade_db`.`UserDeviceDetails` (
                                                     `id` bigint NOT NULL AUTO_INCREMENT,
                                                     `userId` bigint NOT NULL,
                                                     `role` varchar(255) DEFAULT NULL,
                                                     `deviceToken` longtext NOT NULL,
                                                     `ip` varchar(255) DEFAULT NULL,
                                                     `userAgent` varchar(255) DEFAULT NULL,
                                                     `createdAt` datetime NOT NULL,
                                                     `updatedAt` datetime DEFAULT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE KEY `id` (`id`),
                                                     KEY `userId` (`userId`),
                                                     CONSTRAINT `UserDeviceDetails_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `sure_trade_db`.`SupportedGiftCards` (`id`, `name`, `image`, `currency`) VALUES
                                                                                         ('1', 'Amazon', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Famazon_image.png?alt=media&token=f354ae5d-b4fd-466c-b08a-883a71e0abb0', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('10', 'Nintendo', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fnintendo.png?alt=media&token=dac274eb-484e-4d1e-80b4-5ad217d251bc', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('11', 'Paypal', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fpaypal.jpeg?alt=media&token=e341a280-e1f7-4d28-bcb6-0c69243d3f88', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "BRL"]'),
                                                                                         ('12', 'Pi', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fpi_image.png?alt=media&token=5297ef09-a05e-4a51-a568-e52ed8272cb4', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('13', 'Razor', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Frazor_image.png?alt=media&token=33a8490a-be4b-4b7c-b214-622e61a89e2e', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('14', 'Ripple', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fripple.png?alt=media&token=d060ce6e-9299-4da9-9c35-495466f61303', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('15', 'Bitcoin', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fbitcoin.jpg?alt=media&token=a86c9f6a-4c73-444e-8c4c-deefa6af0b09', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "BRL"]'),
                                                                                         ('16', 'Bamba', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fphoto_2023-07-18_16-05-46.jpg?alt=media&token=67cdd44e-2bb6-431f-992e-547cf830be64', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('17', 'Vanilla', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fvanilla_image.png?alt=media&token=6f322727-fb4a-463a-a758-c2bccce10371', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('18', 'Walmart', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fwalmart_image.png?alt=media&token=a542089b-6a92-4f7b-9a41-3c614c71e675', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('19', 'GameStar Reward Card', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fgamestar.png?alt=media&token=ed3571ee-3b5a-4824-b863-fba1d93d74d7', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('2', 'Apple', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fapple_image.png?alt=media&token=add7daa3-6973-4aca-8167-bb9b0fb044ba', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('20', 'Sure Trade Reward Card', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2FsureTrade.png?alt=media&token=c9b23be3-b646-4440-a1b8-d38af5f75509', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "NGN", "BRL"]'),
                                                                                         ('21', 'Chipper Cash', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlxROgpjuukfHRG5bVkpWp9Y6kcE1PLja5fA&usqp=CAU', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL", "NGN", "GHS"]'),
                                                                                         ('22', 'Ebay', 'https://giftcardshub.com.ng/wp-content/uploads/2021/05/ebaaay-1200x675.jpg', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL", "NGN", "GHS"]'),
                                                                                         ('3', 'Binance', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fbinance.png?alt=media&token=a73d61db-3622-42f4-8a33-38c08430db72', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('4', 'Google', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fgoogle_image.png?alt=media&token=ab5358d8-a8cf-4020-ae27-5216dec7b434', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('5', 'Netflix', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fnetflix-gift-card.webp?alt=media&token=75ef92de-5e9a-430c-a80f-6484d072954e', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('6', 'Spotify', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fspotify.jpeg?alt=media&token=75adb77b-c4a3-4c4d-92b9-da4f5b0fedf3', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('7', 'Steam', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fsteam_image.png?alt=media&token=3469deed-caa1-418d-a206-6e55653b0422', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('8', 'Xbox', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fxbox_image.png?alt=media&token=be9c8b24-939e-45ff-867d-a9594f027153', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]'),
                                                                                         ('9', 'Playstation', 'https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fplaystation_image.png?alt=media&token=2f066fd0-b0e9-4f61-b54a-fe4f06542ac3', '["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "INR", "BRL"]');
