server:
  port: 4006
  servlet:
      context-path: /api/v2
  error:
    include-binding-errors: always
    include-message: always

spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  profiles:
    active: dev