name: user-service-prod-pipeline

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: user-service-prod-runner

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Build with Maven
        run: ./gradlew build -X

      - name: Deploy to VM
        run: |
          sudo chmod +x ./deploy-prod.sh
          sudo ./deploy-prod.sh

      
