name: user-service-dev-pipeline

on:
  push:
    branches: [ "development" ]
#  pull_request:
#    branches: [ "development" ]

jobs:
  build:

    runs-on: user-service-dev-runner

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to VM
        run: |
          sudo chmod +x ./deploy-dev.sh
          sudo ./deploy-dev.sh

      
