name: user-service-dev-pipeline

on:
  push:
    branches: [ "development" ]
#  pull_request:
#    branches: [ "development" ]

jobs:
  build:

    runs-on: user-service-dev-runner

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: /home/ubuntu/.sdkman/candidates/maven/current/bin/mvn clean package -X

      - name: Deploy to VM
        run: |
          sudo chmod +x ./deploy-dev.sh
          sudo ./deploy-dev.sh

      
